Lists

In [1]:
movies = ["Inception", "Interstellar", "Titanic", "Avatar", "Joker"]

# First and last movie
print("First movie:", movies[0])
print("Last movie:", movies[-1])

# Add and remove
movies.append("Avengers")
movies.pop(1)

# Sort
movies.sort()
print("Sorted list:", movies)

# Length and check
print("Length:", len(movies))
print("Is 'Titanic' present?", "Titanic" in movies)

First movie: Inception
Last movie: Joker
Sorted list: ['Avatar', 'Avengers', 'Inception', 'Joker', 'Titanic']
Length: 5
Is 'Titanic' present? True


Tuples

In [19]:
cities = ("Chennai", "Mumbai", "Delhi", "Bangalore", "Hyderabad")

print("Second city:", cities[1])
print("Fourth city:", cities[3])

# Trying to change value (will give error)

# cities[0] = "Kolkata"
# This gives error because tuples are immutable (cannot be changed after creation)

# Unpacking
c1, c2, c3, c4, c5 = cities
print(c1, c2, c3, c4, c5)

# Convert to list and back
city_list = list(cities)
city_list.append("Kolkata")
cities = tuple(city_list)

print("Updated tuple:", cities)

Second city: Mumbai
Fourth city: Bangalore
Chennai Mumbai Delhi Bangalore Hyderabad
Updated tuple: ('Chennai', 'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Kolkata')


Dictionary

In [17]:
student = {
    "name": "Sathya",
    "age": 18,
    "grade": "A",
    "city": "Madurai"
}

print("Keys:", list(student.keys()))
print("Values:", list(student.values()))
print("Items:", list(student.items()))

# Update and add
student["grade"] = "A+"
student["email"] = "zylan6476@gmail.com"

# Delete
del student["city"]

print("Final dictionary:", student)

Keys: ['name', 'age', 'grade', 'city']
Values: ['Sathya', 18, 'A', 'Madurai']
Items: [('name', 'Sathya'), ('age', 18), ('grade', 'A'), ('city', 'Madurai')]
Final dictionary: {'name': 'Sathya', 'age': 18, 'grade': 'A+', 'email': 'zylan6476@gmail.com'}


Set

In [4]:
weekday = {"Math", "Science", "English"}
weekend = {"English", "Sports", "Art"}

print("Union:", weekday.union(weekend))
print("Intersection:", weekday.intersection(weekend))
print("Difference:", weekday.difference(weekend))

weekday.add("Computer")
weekend.remove("Art")

print("Updated weekday:", weekday)
print("Updated weekend:", weekend)

print("Is 'Math' present?", "Math" in weekday or "Math" in weekend)

Union: {'Science', 'Sports', 'Math', 'Art', 'English'}
Intersection: {'English'}
Difference: {'Science', 'Math'}
Updated weekday: {'Computer', 'Science', 'English', 'Math'}
Updated weekend: {'Sports', 'English'}
Is 'Math' present? True


Functions

In [5]:
def greet(name):
    print(f"Hello, {name}! Welcome to Day 2.")

def add_numbers(a, b):
    return a + b

def find_max(a, b, c):
    return max(a, b, c)

def is_even(num):
    return num % 2 == 0

greet("Sathya")
print(add_numbers(5, 10))
print(find_max(3, 7, 5))
print(is_even(4))

Hello, Sathya! Welcome to Day 2.
15
7
True


Default Parameters

In [6]:
def introduce(name, language="Python"):
    print(f"{name} is learning {language}.")

introduce("Sathya")
introduce("Sathya", "SQL")

def calculate_discount(price, discount=10):
    return price - (price * discount / 100)

print(calculate_discount(1000))

Sathya is learning Python.
Sathya is learning SQL.
900.0


Conditional Statements

In [7]:
num = int(input("Enter a number: "))

if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

score = int(input("Enter score: "))

if score >= 90:
    print("Grade A")
elif score >= 80:
    print("Grade B")
elif score >= 70:
    print("Grade C")
elif score >= 60:
    print("Grade D")
else:
    print("Grade F")

year = int(input("Enter year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("Leap Year")
else:
    print("Not a Leap Year")

Enter a number: 7
Positive
Enter score: 90
Grade A
Enter year: 2026
Not a Leap Year


For Loop

In [8]:
for i in range(1, 21):
    print(i)

for i in range(2, 51, 2):
    print(i)

fruits = ["Apple", "Banana", "Mango"]
for i, fruit in enumerate(fruits):
    print(i, fruit)

total = sum(range(1, 101))
print("Sum:", total)

text = "education"
vowels = "aeiou"
count = sum(1 for char in text if char in vowels)
print("Vowel count:", count)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
0 Apple
1 Banana
2 Mango
Sum: 5050
Vowel count: 5


NumPy

In [9]:
import numpy as np

1D Arrays

In [10]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

print(np.zeros(10))
print(np.ones(10))
print(np.arange(1, 21))
print(np.linspace(0, 1, 7))
print(np.random.randint(1, 100, 8))

[10 20 30 40 50]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
[31 85 20 78 99 38 67 78]


2D Arrays

In [11]:
print(np.zeros((3,3)))
print(np.eye(3))
print(np.full((4,4), 7))
print(np.random.rand(3,4))

custom = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(custom)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0.89273994 0.58559378 0.33762882 0.49340002]
 [0.75105192 0.52945855 0.27227146 0.81152672]
 [0.75077959 0.37383302 0.749755   0.14445785]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Attributes

In [12]:
arr = np.random.rand(4,5)

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

2
(4, 5)
20
float64
8
160


Data Types in Arrays

In [13]:
# Integer array
arr_int = np.array([1, 2, 3, 4])
print("Integer dtype:", arr_int.dtype)

# Float array
arr_float = np.array([1.1, 2.2, 3.3])
print("Float dtype:", arr_float.dtype)

# Convert int to float
arr_converted = arr_int.astype(float)
print("Before:", arr_int.dtype)
print("After:", arr_converted.dtype)

# Mixed values
arr_mixed = np.array([1, 2.5, 3])
print("Mixed dtype:", arr_mixed.dtype)

# String array
arr_str = np.array(["a", "b", "c"], dtype=str)
print("String dtype:", arr_str.dtype)

Integer dtype: int64
Float dtype: float64
Before: int64
After: float64
Mixed dtype: float64
String dtype: <U1


Special Array Functions

In [14]:
# Zeros and change middle value
arr = np.zeros(10)
arr[5] = 99
print(arr)

# arange with step
print(np.arange(0, 51, 5))

# Identity matrix diagonal
identity = np.eye(5)
print("Diagonal:", np.diag(identity))

# Vertical stack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Vstack:\n", np.vstack((a, b)))

# Horizontal stack
print("Hstack:", np.hstack((a, b)))

[ 0.  0.  0.  0.  0. 99.  0.  0.  0.  0.]
[ 0  5 10 15 20 25 30 35 40 45 50]
Diagonal: [1. 1. 1. 1. 1.]
Vstack:
 [[1 2 3]
 [4 5 6]]
Hstack: [1 2 3 4 5 6]


Indexing & Slicing

In [15]:
arr = np.arange(1, 16)

print("First 5:", arr[:5])
print("Last 3:", arr[-3:])
print("Alternate:", arr[::2])

# 2D array
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print("Element (2nd row, 3rd col):", arr2d[1,2])
print("Second row:", arr2d[1])
print("Third column:", arr2d[:,2])

First 5: [1 2 3 4 5]
Last 3: [13 14 15]
Alternate: [ 1  3  5  7  9 11 13 15]
Element (2nd row, 3rd col): 6
Second row: [4 5 6]
Third column: [3 6 9]


Basic Array Operations

In [16]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# Multiply without loop
arr = np.arange(1, 11)
print("Multiply by 3:", arr * 3)

# Square root
arr_sqrt = np.array([4, 9, 16, 25, 36])
print("Square root:", np.sqrt(arr_sqrt))

# Stats
arr_stats = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr_stats))
print("Mean:", np.mean(arr_stats))
print("Min:", np.min(arr_stats))
print("Max:", np.max(arr_stats))

# Row & column sum
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print("Row sum:", np.sum(arr2d, axis=1))
print("Column sum:", np.sum(arr2d, axis=0))

Addition: [6 6 6 6 6]
Subtraction: [-4 -2  0  2  4]
Multiplication: [5 8 9 8 5]
Division: [0.2 0.5 1.  2.  5. ]
Multiply by 3: [ 3  6  9 12 15 18 21 24 27 30]
Square root: [2. 3. 4. 5. 6.]
Sum: 15
Mean: 3.0
Min: 1
Max: 5
Row sum: [ 6 15 24]
Column sum: [12 15 18]
